include:
  - database.yml

services:
  backend:
    build: ./git/backend
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/fs-backend
      JWT_SECRET_KEY: ${JWT_SECRET_KEY:-secret}
      JWT_ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
      REFRESH_TOKEN_EXPIRE_DAYS: 7
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build: ./git/frontend
    env_file:
      - .env
    environment:
      BACKEND_URL: http://backend:3001
      HOST: 0.0.0.0
      ORIGIN: ${ORIGIN}
    depends_on:
      - backend

  # Nginx reverse proxy
  nginx:
    build: ./nginx
    profiles: ["prod"]
    env_file:
      - .env
    environment:
      SEED: ${SEED}
      HOST: ${HOST}
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend

    extra_hosts:
      - "host.docker.internal:host-gateway"